In [48]:
import numpy as np
import pandas as pd
from pandas import DataFrame as df
# pd.set_option('display.max_rows', 500)
# pd.set_option('display.max_columns', 500)

In [84]:
a = np.random.randint(2, size = (500, 7),dtype = "int")

#a = print(a)

a = np.concatenate( (np.arange(500).reshape(500,1), a) , axis = 1)
a = np.concatenate((a, np.random.randint(1, 6, size = (500,1)), np.random.randint(31, 81, size = (500,1)) * 10), axis = 1)
a = np.concatenate(([['Restaurant id', 'South Indian', 'North Indian', 'Punjabi', 'Chinese', 'Italian', 'Mughalai', 'Kebab', 'Ratings', 'Cost of Two']],a), axis = 0)

pd.DataFrame(a).to_csv("Restaurant_vector", header= None, index=None)
data = pd.read_csv('Restaurant_vector.csv')

b = np.random.randint(-4,6,size=(4000,500))
b = np.concatenate((np.arange(500).reshape(1,500), b), axis = 0)
b = np.concatenate((np.arange(4001).reshape(4001,1), b), axis = 1)
b[b < 0] = 0
b[0][0] = -1;
print(b)
pd.DataFrame(b).to_csv("User_restaurant_dataset", header= None, index=None)
data1 = pd.read_csv('User_restaurant_dataset')

[[  -1    0    1 ...  497  498  499]
 [   1    0    0 ...    0    0    1]
 [   2    3    0 ...    0    4    3]
 ...
 [3998    0    5 ...    0    5    2]
 [3999    0    0 ...    2    3    0]
 [4000    0    3 ...    0    4    1]]


In [85]:
print(data1)

        -1  0  1  2  3  4  5  6  7  8 ...   490  491  492  493  494  495  496  \
0        1  0  0  0  1  0  0  0  2  0 ...     4    0    4    0    0    5    3   
1        2  3  0  5  1  0  2  0  0  0 ...     0    2    1    0    1    0    0   
2        3  1  4  1  1  0  1  0  5  0 ...     0    5    0    2    0    0    5   
3        4  0  0  0  4  0  4  2  0  3 ...     0    5    0    0    4    0    0   
4        5  0  2  3  2  3  5  0  0  0 ...     0    0    0    0    0    0    4   
5        6  1  1  0  0  2  0  0  0  0 ...     5    3    0    1    5    0    4   
6        7  3  0  4  5  1  4  0  0  0 ...     0    0    0    0    0    0    0   
7        8  2  0  5  0  0  2  5  0  0 ...     0    0    4    0    0    0    2   
8        9  0  3  1  5  0  4  0  0  5 ...     3    1    0    4    0    3    0   
9       10  2  0  0  0  0  5  0  0  0 ...     5    0    5    2    4    5    5   
10      11  0  1  5  5  3  1  1  2  0 ...     0    1    0    0    0    5    0   
11      12  0  3  0  1  4  0

In [66]:
data1.describe()


0          0.1            1            2            3  \
count  4000.000000  4000.000000  4000.000000  4000.000000  4000.000000   
mean   2000.500000     1.526250     1.506500     1.537250     1.486500   
std    1154.844867     1.817729     1.810739     1.818774     1.801841   
min       1.000000     0.000000     0.000000     0.000000     0.000000   
25%    1000.750000     0.000000     0.000000     0.000000     0.000000   
50%    2000.500000     1.000000     0.000000     1.000000     0.000000   
75%    3000.250000     3.000000     3.000000     3.000000     3.000000   
max    4000.000000     5.000000     5.000000     5.000000     5.000000   

                 4            5            6          7            8  \
count  4000.000000  4000.000000  4000.000000  4000.0000  4000.000000   
mean      1.483500     1.507000     1.504000     1.4925     1.483000   
std       1.811366     1.803403     1.808812     1.8260     1.791093   
min       0.000000     0.000000     0.000000     0.0000     0.000000   
25%       0.000000     0.000000     0.000000     0.0000     0.000000   
50%       0.000000     1.000000     0.000000     0.0000     1.000000   
75%       3.000000     3.000000     3.000000     3.0000     3.000000   
max       5.000000     5.000000     5.000000     5.0000     5.000000   

          ...               490          491          492          493  \
count     ...       4000.000000  4000.000000  4000.000000  4000.000000   
mean      ...          1.548250     1.480750     1.471500     1.464500   
std       ...          1.822636     1.776068     1.781006     1.786488   
min       ...          0.000000     0.000000     0.000000     0.000000   
25%       ...          0.000000     0.000000     0.000000     0.000000   
50%       ...          1.000000     1.000000     0.000000     0.000000   
75%       ...          3.000000     3.000000     3.000000     3.000000   
max       ...          5.000000     5.000000     5.000000     5.000000   

               494          495          496          497          498  \
count  4000.000000  4000.000000  4000.000000  4000.000000  4000.000000   
mean      1.524250     1.543250     1.504500     1.478000     1.494000   
std       1.810451     1.821664     1.797856     1.793689     1.781364   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       1.000000     1.000000     1.000000     0.000000     1.000000   
75%       3.000000     3.000000     3.000000     3.000000     3.000000   
max       5.000000     5.000000     5.000000     5.000000     5.000000   

               499  
count  4000.000000  
mean      1.445750  
std       1.764465  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       3.000000  
max       5.000000  

[8 rows x 501 columns]